// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: example.proto

package pb_gen

import (
	reflect "reflect"
	sync "sync"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExampleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Alpha   string `protobuf:"bytes,1,opt,name=alpha,proto3" json:"alpha,omitempty" form:"alpha"`
	Bravo   string `protobuf:"bytes,2,opt,name=bravo,proto3" json:"bravo,omitempty" form:"bravo"`
	Charlie string `protobuf:"bytes,3,opt,name=charlie,proto3" json:"charlie,omitempty" form:"charlie"`
	Delta   string `protobuf:"bytes,4,opt,name=delta,proto3" json:"delta,omitempty" form:"delta"`
	Echo    int64  `protobuf:"varint,5,opt,name=echo,proto3" json:"echo,omitempty" form:"echo"`
}

func (x *ExampleRequest) Reset() {
	*x = ExampleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_example_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExampleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleRequest) ProtoMessage() {}

func (x *ExampleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_example_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleRequest.ProtoReflect.Descriptor instead.
func (*ExampleRequest) Descriptor() ([]byte, []int) {
	return file_common_example_proto_rawDescGZIP(), []int{0}
}

func (x *ExampleRequest) GetAlpha() string {
	if x != nil {
		return x.Alpha
	}
	return ""
}

func (x *ExampleRequest) GetBravo() string {
	if x != nil {
		return x.Bravo
	}
	return ""
}

func (x *ExampleRequest) GetCharlie() string {
	if x != nil {
		return x.Charlie
	}
	return ""
}

func (x *ExampleRequest) GetDelta() string {
	if x != nil {
		return x.Delta
	}
	return ""
}

func (x *ExampleRequest) GetEcho() int64 {
	if x != nil {
		return x.Echo
	}
	return 0
}

type ExampleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Foxtrot string `protobuf:"bytes,1,opt,name=foxtrot,proto3" json:"foxtrot,omitempty" form:"foxtrot"`
	Golf    string `protobuf:"bytes,2,opt,name=golf,proto3" json:"golf,omitempty" form:"golf"`
	Hotel   string `protobuf:"bytes,3,opt,name=hotel,proto3" json:"hotel,omitempty" form:"hotel"`
	India   int64  `protobuf:"varint,4,opt,name=india,proto3" json:"india,omitempty" form:"india"`
}

func (x *ExampleResponse) Reset() {
	*x = ExampleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_example_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExampleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExampleResponse) ProtoMessage() {}

func (x *ExampleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_example_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExampleResponse.ProtoReflect.Descriptor instead.
func (*ExampleResponse) Descriptor() ([]byte, []int) {
	return file_common_example_proto_rawDescGZIP(), []int{1}
}

func (x *ExampleResponse) GetFoxtrot() string {
	if x != nil {
		return x.Foxtrot
	}
	return ""
}

func (x *ExampleResponse) GetGolf() string {
	if x != nil {
		return x.Golf
	}
	return ""
}

func (x *ExampleResponse) GetHotel() string {
	if x != nil {
		return x.Hotel
	}
	return ""
}

func (x *ExampleResponse) GetIndia() int64 {
	if x != nil {
		return x.India
	}
	return 0
}

var File_common_example_proto protoreflect.FileDescriptor

var file_common_example_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2e, 0x63, 0x6e,
	0x63, 0x5f, 0x69, 0x64, 0x6c, 0x22, 0x80, 0x01, 0x0a, 0x0e, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x6c, 0x70, 0x68,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x61, 0x6c, 0x70, 0x68, 0x61, 0x12, 0x14,
	0x0a, 0x05, 0x62, 0x72, 0x61, 0x76, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62,
	0x72, 0x61, 0x76, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x72, 0x6c, 0x69, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x68, 0x61, 0x72, 0x6c, 0x69, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x64, 0x65, 0x6c, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x64,
	0x65, 0x6c, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x65, 0x63, 0x68, 0x6f, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x04, 0x65, 0x63, 0x68, 0x6f, 0x22, 0x6b, 0x0a, 0x0f, 0x45, 0x78, 0x61, 0x6d,
	0x70, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x66,
	0x6f, 0x78, 0x74, 0x72, 0x6f, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x66, 0x6f,
	0x78, 0x74, 0x72, 0x6f, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x6f, 0x6c, 0x66, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x67, 0x6f, 0x6c, 0x66, 0x12, 0x14, 0x0a, 0x05, 0x68, 0x6f, 0x74,
	0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x68, 0x6f, 0x74, 0x65, 0x6c, 0x12,
	0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x69, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x69, 0x6e, 0x64, 0x69, 0x61, 0x42, 0x26, 0x5a, 0x24, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x64, 0x61,
	0x76, 0x65, 0x78, 0x2e, 0x70, 0x77, 0x2f, 0x68, 0x6f, 0x72, 0x75, 0x73, 0x2f, 0x74, 0x6f, 0x77,
	0x65, 0x72, 0x5f, 0x73, 0x64, 0x6b, 0x2f, 0x70, 0x62, 0x5f, 0x67, 0x65, 0x6e, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_example_proto_rawDescOnce sync.Once
	file_common_example_proto_rawDescData = file_common_example_proto_rawDesc
)

func file_common_example_proto_rawDescGZIP() []byte {
	file_common_example_proto_rawDescOnce.Do(func() {
		file_common_example_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_example_proto_rawDescData)
	})
	return file_common_example_proto_rawDescData
}

var file_common_example_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_example_proto_goTypes = []interface{}{
	(*ExampleRequest)(nil),  // 0: horus.cnc_idl.ExampleRequest
	(*ExampleResponse)(nil), // 1: horus.cnc_idl.ExampleResponse
}
var file_common_example_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_example_proto_init() }
func file_common_example_proto_init() {
	if File_common_example_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_example_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExampleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_example_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExampleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_example_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_example_proto_goTypes,
		DependencyIndexes: file_common_example_proto_depIdxs,
		MessageInfos:      file_common_example_proto_msgTypes,
	}.Build()
	File_common_example_proto = out.File
	file_common_example_proto_rawDesc = nil
	file_common_example_proto_goTypes = nil
	file_common_example_proto_depIdxs = nil
}
